# Generated by Django 3.0.4 on 2020-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='come_funziona',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='locale',
            name='categoria',
            field=models.CharField(choices=[('AL', 'Alimentari'), ('PA', 'Panificio'), ('GE', 'Gelateria'), ('FV', 'Frutta e verdura'), ('PI', 'Pizzeria'), ('RI', 'Ristorante'), ('PS', 'Pasticceria')], default='AL', max_length=2),
        ),
    ]
